version: "3.2"

services:
  radarr:
    image: ghcr.io/linuxserver/radarr:latest
    logging:
      driver: json-file
    networks:
      backend:
    ports:
      - 7878:7878
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - C:/media-stack/radarrconfig:/config
      - C:/media-stack/movies:/movies
      - C:/media-stack/usenet:/downloads
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    logging:
      driver: json-file
    networks:
      backend:
    ports:
      - 8989:8989
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - C:/media-stack/sonarrconfig:/config
      - C:/media-stack/tvseries:/tv
      - C:/media-stack/usenet:/downloads
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd:latest
    logging:
      driver: json-file
    networks:
      backend:
    ports:
      - 8088:8080
      - 9090:9090
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - C:/media-stack/sabnzbdconfig:/config
      - C:/media-stack/usenet:/downloads
      - C:/media-stack/usenet-incomplete:/incomplete-downloads
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  overseerr:
    image: ghcr.io/linuxserver/overseerr:latest
    logging:
      driver: json-file
    networks:
      backend:
    ports:
      - 5055:5055
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - C:/media-stack/overseerrconfig:/config
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  backend: